language: common-lisp
sudo: required

install:
  - curl -L https://raw.githubusercontent.com/dbym4820/roswell/master/scripts/install-for-ci.sh | sh

  
script:
  - ros -s prove -e '(or (prove:run :photon-test) (uiop:quit -1))'
