language: common-lisp
sudo: false

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t
  matrix:
    - LISP=sbcl-bin COVERALLS=true

addons:
  apt:
    packages:
      - xfvb

install:
  # Roswell & coveralls
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls
  # Clone some libraries
  - git clone https://github.com/ceramic/electron-tools ~/lisp/electron-tools
  - git clone https://github.com/ceramic/copy-directory ~/lisp/copy-directory
  - git clone https://github.com/ceramic/remote-js ~/lisp/remote-js
  - git clone https://github.com/ceramic/trivial-ws ~/lisp/trivial-ws
  - git clone https://github.com/ceramic/trivial-compress ~/lisp/trivial-compress
  - git clone https://github.com/eudoxia0/trivial-extract ~/lisp/trivial-extract
  # Set up a virtual X framebuffer
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb time to start

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

before_script:
  - ros --version
  - ros config

script:
  - ros -e '(ql:quickload (list :cl-coveralls :ceramic-test))'
        -e '(setf fiveam:*debug-on-error* t
                  fiveam:*debug-on-failure* t)'
       -e '(coveralls:with-coveralls (:exclude (list "src/error.lisp"
                                                     "src/os.lisp"
                                                     "src/file.lisp"
                                                     "src/quit.lisp"
                                                     "t"))
             (ceramic-test:run-tests))'

notifications:
  email:
    - eudoxiahp@gmail.com
